title: Welcome to wherby's blog!
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tao Zhou # add your name
author-img: tao.jpg # add your photo
about-author: Software Engineer(Scala | Mesos | Akka | Cassandra | Kafka | C# |Spark ) # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: wherby  # add your Github handle
linkedin: tao-zhou-92102641/ # add your Linkedin handle
email: 187225577@qq.com # add your Email address

# Disqus
discus-identifier: wherby # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
